[server]
bind = [
    "tcp",
    "0.0.0.0:80",
]
transport = "websocket"
resolve_ipv6 = false
tcp_nodelay = true
file_raw_mode = false
use_real_ip_headers = true
non_ws_response = ":3"
max_message_size = 65536
log_level = "INFO"
runtime = "singlethread"

[wisp]
allow_wsproxy = true
buffer_size = 128
prefix = ""
wisp_v2 = true
extensions = [
    "udp",
    "motd",
]
password_extension_required = true
certificate_extension_required = false
read_limit = 10000000
write_limit = 10000000

[stream]
tcp_nodelay = true
buffer_size = 131072
allow_udp = true
allow_wsproxy_udp = false
dns_servers = []
allow_direct_ip = true
allow_loopback = true
allow_multicast = true
allow_global = true
allow_non_global = true
allow_tcp_hosts = []
block_tcp_hosts = []
allow_udp_hosts = []
block_udp_hosts = []
allow_hosts = []
block_hosts = []
allow_ports = []
block_ports = []
